redis_host: cache.mrahman.xyz
redis_password: "{{ vault_redis_password }}"
redis_port: 6379

postgres_host: data.mrahman.xyz
postgres_user: "postgres"
postgres_root_password: "{{ vault_postgres_root_password }}"
postgres_port: 5432

# Ingress (Nginx Reverse Proxy)
ingress_root_domain: "mrahman.xyz"
ingress_cert_email: "masudjuly02@gmail.com"
ingress_sites:
  - domain: "gateway.mrahman.xyz"
    upstream: "http://10.66.0.1"
    force_ip_header: true
  - domain: "proxmox.mrahman.xyz"
    upstream: "https://10.66.0.10:8006"
    websocket: true
  - domain: "adguard.mrahman.xyz"
    upstream: "http://10.66.0.253:3000"
    websocket: false

porkbun_api_key: "{{ vault_porkbun_api_key }}"
porkbun_secret_key: "{{ vault_porkbun_secret_key }}"

# Expense Tracker Bot Config
expense_bot_version: "v1.3.1"
expense_bot_token: "{{ vault_expense_bot_token }}"
expense_bot_openrouter_key: "{{ vault_expense_bot_openrouter_key }}"
expense_bot_user: "masudur_rahman"

# Database Config
expense_db_host: "{{ postgres_host }}"
expense_db_port: "{{ postgres_port }}"
expense_db_user: "{{ postgres_user }}"
expense_db_pass: "{{ postgres_root_password }}"
expense_db_name: "expense"

# Redis / Cache Config
expense_cache_type: "redis" # Options: redis, map
expense_redis_host: "{{ redis_host }}"
expense_redis_port: "{{ redis_port }}"
expense_redis_pass: "{{ redis_password }}"

# Uptime Kuma Monitors (reference for manual UI setup)
monitoring_uptime_kuma_monitors:
  - name: "Proxmox"
    type: "http"
    url: "https://10.66.0.10:8006"
    accepted_statuscodes: ["401"]
    ignoreTls: true
  - name: "AdGuard DNS"
    type: "http"
    url: "http://10.66.0.253:3000"
  - name: "Gateway/Router"
    type: "ping"
    hostname: "10.66.0.1"
  - name: "Nginx Portal"
    type: "http"
    url: "http://10.66.0.201"
  - name: "PostgreSQL"
    type: "port"
    hostname: "10.66.0.20"
    port: 5432
  - name: "Redis"
    type: "port"
    hostname: "10.66.0.20"
    port: 6379
  - name: "Expense Tracker Bot"
    type: "http"
    url: "http://10.66.0.50:8080"
  - name: "Netdata"
    type: "http"
    url: "http://10.66.0.40:19999"
