# Ingress (Nginx Reverse Proxy)
ingress_root_domain: "mrahman.xyz"
ingress_cert_email: "masudjuly02@gmail.com"
ingress_sites:
- domain: "gateway.mrahman.xyz"
  upstream: "http://10.66.0.1"
  force_ip_header: true
- domain: "proxmox.mrahman.xyz"
  upstream: "https://10.66.0.10:8006"
  websocket: true
- domain: "adguard.mrahman.xyz"
  upstream: "http://10.66.0.253:3000"
  websocket: false

porkbun_api_key: "porkbun-api-key"
porkbun_secret_key: "porkbun-secret-key"

# Expense Tracker Bot Config
expense_bot_version: "v1.3.0-rc.2"
expense_bot_token: "6411966391:AAEdr7FoasT11TTgaJ_albzjJP-VkLkxSRE"
expense_bot_openrouter_key: "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"
expense_bot_user: "masudur_rahman"

# Database Config
expense_db_user: "postgres"
expense_db_pass: "postgres"
expense_db_name: "expense"

# Redis / Cache Config
expense_cache_type: "redis" # Options: redis, map
expense_redis_pass: "redis"
expense_redis_port: "6379"
