---
monitoring_uptime_kuma_version: "1"
monitoring_netdata_version: "stable"
monitoring_uptime_kuma_port: 3001
monitoring_netdata_port: 19999

# Required (set in group_vars/all.yml):
# monitoring_netdata_api_key: "{{ vault_monitoring_netdata_api_key }}"
