[expense-tracker]
expense-tracker-01 ansible_host=10.66.0.55 ansible_user=unknown

[test-vm]
test-vm-01 ansible_host=10.66.0.50 ansible_user=unknown
test-vm-02 ansible_host=10.66.0.51 ansible_user=unknown

