[data]
data-01 ansible_host=10.66.0.20 ansible_user=unknown

[expense-tracker]
expense-tracker-01 ansible_host=10.66.0.30 ansible_user=unknown

[monitoring]
monitoring-01 ansible_host=10.66.0.40 ansible_user=unknown

[portal]
portal-01 ansible_host=10.66.0.51 ansible_user=unknown

[k8s]
olympus ansible_connection=local kubeconfig=/Users/masud/go/src/github.com/masudur-rahman/homelab-forge/inventories/compute/files/olympus_kubeconfig.yaml talosconfig=/Users/masud/go/src/github.com/masudur-rahman/homelab-forge/inventories/compute/files/olympus_talosconfig.yaml

[talos_nodes]
olympus-ctrl-01 ansible_host=10.66.0.61 cluster=olympus ansible_connection=local
olympus-ctrl-02 ansible_host=10.66.0.62 cluster=olympus ansible_connection=local
olympus-ctrl-03 ansible_host=10.66.0.63 cluster=olympus ansible_connection=local
olympus-worker-01 ansible_host=10.66.0.70 cluster=olympus ansible_connection=local
olympus-worker-02 ansible_host=10.66.0.71 cluster=olympus ansible_connection=local
olympus-worker-03 ansible_host=10.66.0.72 cluster=olympus ansible_connection=local
olympus-worker-04 ansible_host=10.66.0.73 cluster=olympus ansible_connection=local
olympus-worker-05 ansible_host=10.66.0.74 cluster=olympus ansible_connection=local

