---
- name: Register AdGuard Health Check
  copy:
    dest: /etc/keepalived/checks.d/adguard.sh
    mode: '0755'
    content: |
      #!/bin/bash
      if host google.com 127.0.0.1 > /dev/null 2>&1; then
          exit 0
      else
          exit 1
      fi
