---
- name: Prepare AdGuard Environment
  ansible.builtin.include_tasks: prepare.yml

- name: Install AdGuard Home
  ansible.builtin.include_tasks: install.yml

- name: Configure AdGuard Service
  ansible.builtin.include_tasks: configure.yml

- name: Setup HA Monitoring
  ansible.builtin.include_tasks: ha.yml
