---
- name: Prepare AdGuard Environment
  include_tasks: prepare.yml

- name: Install AdGuard Home
  include_tasks: install.yml

- name: Configure AdGuard Service
  include_tasks: configure.yml

- name: Setup HA Monitoring
  include_tasks: ha.yml

# - name: Configure DNS Records via API
#   include_tasks: configure_dns.yml
#   tags: dns_records
