---
- name: Configure Base System
  ansible.builtin.include_tasks: system.yml
  tags:
    - system

- name: Configure DNS
  ansible.builtin.include_tasks: dns.yml
  when: "'gateway' not in group_names"
  tags:
    - dns

- name: Setup Docker Engine
  ansible.builtin.include_tasks: docker.yml
  tags:
    - docker
