---
- name: Install Keepalived
  ansible.builtin.apt:
    name: keepalived
    state: present

- name: Enable Non-Local Bind
  ansible.posix.sysctl:
    name: net.ipv4.ip_nonlocal_bind
    value: '1'
    sysctl_set: true
    state: present

- name: Create Checks Directory
  ansible.builtin.file:
    path: /etc/keepalived/checks.d
    state: directory
    mode: '0755'

- name: Discover Health Check Scripts
  ansible.builtin.find:
    paths: /etc/keepalived/checks.d
    patterns: "*.sh"
    file_type: file
  register: floating_ip_discovered_checks

- name: Deploy Dynamic HA Config
  ansible.builtin.template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    mode: '0644'
  notify: Restart Keepalived
