---
- name: Reload Nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded

- name: Run SSL Fetcher
  ansible.builtin.command: "/usr/bin/python3 /usr/local/bin/fetch_ssl_{{ ingress_root_domain }}.py"
  changed_when: true
