---
- name: Install Nginx Service
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: true

- name: Setup SSL Fetcher (Porkbun)
  ansible.builtin.include_tasks: ssl_fetcher.yml

- name: Configure Nginx Reverse Proxy
  ansible.builtin.include_tasks: nginx.yml
