---
- name: Ensure Nginx Configuration Directory Exists
  ansible.builtin.file:
    path: /etc/nginx/conf.d
    state: directory
    mode: '0755'

- name: Upload Domain Configurations
  ansible.builtin.template:
    src: domain.conf.j2
    dest: "/etc/nginx/conf.d/{{ server.domain }}.conf"
    mode: '0644'
  loop: "{{ ingress_sites }}"
  loop_control:
    loop_var: server
  notify: Reload Nginx

- name: Validate Nginx Configuration
  ansible.builtin.command: nginx -t
  changed_when: false
