---
- name: Install QR Encode (Required for Artifacts)
  ansible.builtin.apt:
    name: qrencode
    state: present

- name: Create Temporary Artifact Directory
  ansible.builtin.file:
    path: /tmp/wg_artifacts
    state: directory
    mode: '0700'

- name: Generate Client Configs (Remote Temp)
  ansible.builtin.template:
    src: client.conf.j2
    dest: "/tmp/wg_artifacts/{{ client.name }}.conf"
    mode: '0600'
  loop: "{{ vpn_wireguard_clients }}"
  loop_control:
    loop_var: client

- name: Generate QR Codes
  ansible.builtin.shell: |
    qrencode -t PNG -o "/tmp/wg_artifacts/{{ client.name }}.png" < "/tmp/wg_artifacts/{{ client.name }}.conf"
  args:
    creates: "/tmp/wg_artifacts/{{ client.name }}.png"
  loop: "{{ vpn_wireguard_clients }}"
  loop_control:
    loop_var: client

- name: Fetch Client Artifacts
  ansible.builtin.fetch:
    src: "/tmp/wg_artifacts/{{ client.0.name }}.{{ client.1 }}"
    dest: "{{ vpn_wireguard_key_path }}/"
    flat: true
  loop: "{{ vpn_wireguard_clients | product(['conf', 'png']) | list }}"
  loop_control:
    loop_var: client

- name: Remove Temporary Artifacts
  ansible.builtin.file:
    path: /tmp/wg_artifacts
    state: absent
