---
- name: Check if server keys exist locally
  ansible.builtin.stat:
    path: "{{ vpn_wireguard_key_path }}/server.key"
  register: vpn_local_server_key
  delegate_to: localhost
  become: false

- name: Generate WireGuard Keys
  when: not vpn_local_server_key.stat.exists
  run_once: true
  block:
    - name: Install WireGuard Tools
      ansible.builtin.apt:
        name: wireguard-tools
        state: present

    - name: Generate Server Private Key
      ansible.builtin.command: wg genkey
      register: vpn_factory_server_private
      changed_when: false

    - name: Derive Server Public Key
      ansible.builtin.shell:
        cmd: set -o pipefail && echo "{{ vpn_factory_server_private.stdout }}" | wg pubkey
        executable: /bin/bash
      register: vpn_factory_server_public
      changed_when: false

    - name: Generate Client Keys
      ansible.builtin.shell:
        cmd: |
          set -o pipefail
          PRIV=$(wg genkey)
          PUB=$(echo "$PRIV" | wg pubkey)
          echo "{\"name\": \"{{ item.name }}\", \"private\": \"$PRIV\", \"public\": \"$PUB\"}"
        executable: /bin/bash
      loop: "{{ vpn_wireguard_clients }}"
      register: vpn_factory_client_keys
      changed_when: false

    - name: Create local key storage
      ansible.builtin.file:
        path: "{{ vpn_wireguard_key_path }}"
        state: directory
        mode: '0700'
      delegate_to: localhost
      become: false

    - name: Save Server Keys Locally
      ansible.builtin.copy:
        content: "{{ item.content }}"
        dest: "{{ vpn_wireguard_key_path }}/{{ item.file }}"
        mode: '0600'
      loop:
        - { file: 'server.key', content: "{{ vpn_factory_server_private.stdout }}" }
        - { file: 'server.pub', content: "{{ vpn_factory_server_public.stdout }}" }
      delegate_to: localhost
      become: false

    - name: Save Client Keys Locally
      ansible.builtin.copy:
        content: "{{ item.0.stdout | from_json | json_query(query_key) }}"
        dest: "{{ vpn_wireguard_key_path }}/{{ item.0.stdout | from_json | json_query('name') }}.{{ ext }}"
        mode: '0600'
      loop: "{{ vpn_factory_client_keys.results | product(['key', 'pub']) | list }}"
      vars:
        ext: "{{ item.1 }}"
        query_key: "{{ 'private' if item.1 == 'key' else 'public' }}"
      when: item.0.stdout is defined
      delegate_to: localhost
      become: false
