---
- name: Ping Host
  ansible.builtin.command: "ping -c 1 -W 1 {{ ansible_host | default(inventory_hostname) }}"
  delegate_to: localhost
  connection: local
  register: ping_result
  failed_when: false
  changed_when: false
