---
- name: Base configuration for compute nodes
  hosts: all
  become: true
  roles:
    - configure_host
    # - ssh

# - name: Talos nodes
#   hosts: talos
#   roles:
#     - talos_node

# - name: Flatcar nodes
#   hosts: flatcar
#   roles:
#     - flatcar_node
