---
- name: Configure Infra Layer Base
  hosts: all
  become: yes
  roles:
   - configure_host

- name: Configure Infrastructure
  hosts: gateway
  become: yes
  roles:
    - role: vpn
      tags:
        - vpn
    - role: ha_vip
      vars:
        ha_vip: "{{ vpn_wireguard_ha_vip }}"
        ha_auth_pass: "{{ vpn_wireguard_ha_auth_pass }}"
        ha_router_id: "{{ vpn_wireguard_ha_router_id }}"
        ha_instance_name: "{{ vpn_wireguard_ha_instance_name }}"
      tags:
        - ha
